---
services:
  # Postgres Database For N8N Persistent Data
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - n8n_network
    expose:
      - "5432" # Only accessible within the Docker network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # PostgreSQL optimizations for 16GB RAM server
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=300
      -c shared_buffers=2GB
      -c effective_cache_size=12GB
      -c work_mem=16MB
      -c maintenance_work_mem=512MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c min_wal_size=1GB
      -c max_wal_size=4GB
    # Resource allocation for PostgreSQL
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "0.5"

  n8n:
    image: n8nio/n8n:1.110.1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Core Configuration
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

      # Database Configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      # Execution Mode
      - EXECUTIONS_MODE=regular

      # Production Configuration
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_URL=https://${N8N_DOMAIN}
      - N8N_EDITOR_BASE_URL=https://${N8N_DOMAIN}
      - NODE_ENV=production

      # Security Configuration
      - N8N_SECURE_COOKIE=false # nginx handles SSL
      - WEBHOOK_TUNNEL_URL= # Disable built-in tunnel service in production

      # Performance Configuration - Optimized for 16GB RAM server
      - N8N_CONCURRENCY_PRODUCTION=${N8N_CONCURRENCY:-25} # 25 threads
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_BINARY_DATA_TTL=120 # 2 hours of TTL for larger server
      - N8N_BINARY_DATA_STORAGE_PATH=/home/node/.n8n/binaryData

      # Execution Data Configuration
      - EXECUTIONS_DATA_PRUNE=true # Enable execution data pruning
      - EXECUTIONS_DATA_MAX_AGE=720 # Keep 30 days of executions data
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true

      # Timezone Configuration
      - TZ=Asia/Jerusalem

      # Additional Settings
      - N8N_METRICS=true # Enable metrics endpoint
      - N8N_DIAGNOSTICS_ENABLED=false # Disable diagnostics in production
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=true # Disable onboarding for production

      # Memory and Performance - Optimized for large server
      - NODE_OPTIONS=--max-old-space-size=6144 # 6GB heap for Node.js

      # Additional performance settings
      - N8N_PUSH_BACKEND=sse # Server-sent events for better performance
      - N8N_PERSONALIZATION_ENABLED=false

    volumes:
      - ./data/n8n:/home/node/.n8n # N8N Temporary Files
    networks:
      - n8n_network
    ports:
      - "5678:5678"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5678/healthz",
        ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    # Resource limits and allocation for N8N
    deploy:
      resources:
        limits:
          memory: 8G # Allow N8N to use up to 8GB
          cpus: "4.0" # Allow up to 4 CPU cores
        reservations:
          memory: 2G # Reserve 2GB minimum
          cpus: "1.0" # Reserve 1 CPU core

networks:
  n8n_network:
    driver: bridge
